services:
  mqtt-broker:
    image: "${IMAGE}"
    container_name: "mqtt-broker"
    restart: "always"
    networks:
      - "reverse-proxy"
    ports:
      - "1883:1883"
    volumes:
      - "./config:/mosquitto/config"
      - "./data:/mosquitto/data"
      - "./log:/mosquitto/log"
    labels:
      - "diun.enable=true"
      - "diun.include_tags=^2\\.\\d+\\.\\d+$"

networks:
  reverse-proxy:
    external: true
